# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37cf756207fae29acf8a44c04ee0a70ead474926ed319c66cc5cdb48e1ff21146a21397a99dc8f5d435212f915b35902dffc3a839e031f3a921abe1a377e0cfc

test:
  secret_key_base: 39a5e43f0739756078db8af58e903d32fa240b809c67f4f3a67a60850897b4c4add346a51fdcdf07e73ba8722f216c5af72e293a97e5692053efa623aa69d861

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
