source 'https://rubygems.org'

  gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
  gem 'pg', '~> 0.18'
  gem 'puma', '~> 3.0'
  gem 'sass-rails', '~> 5.0'
  gem 'uglifier', '>= 1.3.0'
  gem 'coffee-rails', '~> 4.2'
  gem 'jquery-rails'
  gem 'turbolinks', '~> 5'
  gem 'geocoder', '~> 1.4.3'
  gem 'gmaps4rails', '~> 2.1.2'
  gem 'jbuilder', '~> 2.5'
  gem 'bootstrap-generators', '~> 3.3.4'
  gem 'bootstrap-sass', '~> 3.3.6'

  gem 'dotenv-rails', '~> 2.2.1', groups: [:development, :test]

  group :development, :test do
    gem 'byebug', platform: :mri
    gem 'rspec-rails'
    gem 'launchy'
    gem 'pry'
    gem 'shoulda-matchers'
    gem 'capybara'
  end

  group :development do
    gem 'web-console'
    gem 'listen', '~> 3.0.5'
    gem 'spring'
    gem 'spring-watcher-listen', '~> 2.0.0'
  end

  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
